name: CMake

on:
  push:
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker://danger89/cmake:latest

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: make

    - name: Test Avg Main
      working-directory: ${{github.workspace}}/build
      run: ./src/avg-main && ./src/avg-main | grep 15

      - name: Test square-adhoc
      working-directory: ${{github.workspace}}/build
      run: ./src/square-adhoc && ./src/square-adhoc | grep 100
